spring:
  application:
    name: Todo-App
  datasource:
    url: jdbc:postgresql://localhost:5432/pc_todo
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
